# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem "rails", "~> 6.1.4", ">= 6.1.4.1"
# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"
# Use Puma as the app server
gem "puma", "~> 5.0"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem "redis"

gem "identity_cache"
gem "dalli" # To use :mem_cache_store

# Use Active Model has_secure_password
gem "bcrypt", "~> 3.1.7"
gem "cityhash"
gem "data_uri", "~> 0.1.0"
gem "json_web_token", "~> 0.3.5"
gem "jwt"
gem "kaminari-activerecord"
gem "mini_magick"

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

# GraphQL
gem "graphql"
gem "graphql-batch"
gem "graphql-errors"
gem "graphql-pagination"
gem "graphiql-rails"
gem "graphql-rails_logger"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "factory_bot_rails"
  gem "faker"
  gem "rails-erd"
  gem "rspec-rails"

  gem "rubocop", require: false
  gem "rubocop-faker", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-shopify", require: false
end

group :development do
  gem "listen", "~> 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "simplecov", require: false, group: :test
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
