name: API
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: 'mysql'
        env:
            MYSQL_DATABASE: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
      redis:
        image: 'redis:alpine'
        ports:
          - '6379:6379'
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Install dependent libraries
        run: >-
          sudo apt-get install
          nodejs
          build-essential
          default-mysql-client
          default-libmysqlclient-dev
      - name: Bundle install
        run: |
          gem install bundler
          cd api
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          cd api
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          DB_USER: root
          DB_PASSWORD: root
      - name: Run Rubocop
        run: |
          cd api
          rubocop
      - name: Run RSpec
        run: |
          cd api
          COVERAGE=true bundle exec rspec -f j -o tmp/rspec_results.json -f p --require rails_helper
        env:
          RAILS_ENV: test
          DB_USER: root
          Db_PASSWORD: root
      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@v1
        if: always()
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          json-path: tmp/rspec_results.json