name: Client
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        cd client
        npm install
    # - name: Run Prettier
    #   run: |
    #     cd client
    #     yarn run format
    # - name: Run Jest
    #   run: |
    #     cd client
    #     yarn run test